# Uncomment the next line to define a global platform for your project
# platform :ios, '11.2'

target 'checkin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    #pod 'FacebookCore'
    #pod 'FacebookLogin'
    #pod 'FacebookShare'
    #pod 'FBSDKCoreKit'
    
  # Pods for checkin
  pod 'Alamofire', '~> 4.5'
  pod 'Kingfisher', '~> 4.0'
  pod 'SwiftHash'
  pod 'Mailgun-In-Swift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end
